repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: ^data/raw/
      - id: end-of-file-fixer
        exclude: ^data/raw/
      - id: trailing-whitespace
        exclude: ^data/raw/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^data/raw/
      - id: ruff-format
        exclude: ^data/raw/
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
      - id: gitleaks
        exclude: ^data/raw/
