name: Update Wonder Topics

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * 6" # At 18:00 on Saturday
  workflow_dispatch:

jobs:
  update-wonder-topics:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: write # Write access is needed to push changes back to the repository
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          version: "latest"

      - name: Running update script to catalog Wonder into health topics
        run: |
          uv run python -m src.wonder.catalog

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git status
          git config --local user.email "noreply@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/raw/wonder/
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update of raw health changes - $(date +'%Y-%m-%d')"
            git push -u origin main
          fi
